name: Continuous Integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: pip install
      run: |
        pip install git+https://github.com/damoti/stream-controller.git#egg=streamcontroller
        pip install -e .
    - working-directory: tests
      env:
        TEST_OTP: ${{ secrets.TEST_OTP }}
        TEST_OAUTH: ${{ secrets.TEST_OAUTH }}
        TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
      run: python -m unittest discover
