name: Continuous Integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - run: pip install git+https://github.com/damoti/stream-controller.git#egg=streamcontroller
    - run: pip install -e .
    - run: npm install localtunnel
    - working-directory: tests
      env:
        TEST_OTP: ${{ secrets.TEST_OTP }}
        TEST_OAUTH: ${{ secrets.TEST_OAUTH }}
        TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        TEST_USE_LOCALTUNNEL: ${{ github.workspace }}/node_modules/localtunnel/bin/lt.js
      run: python -m unittest discover
